---

- name: Install common utils
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - htop
    - python-software-properties
  become: true
  tags:
    - common

- name: Install Python packages for validating SSL certificates with SNI
  pip:
    name: supervisor
  with_items:
    - ndg-httpsclient
    - pyasn1
    - pyOpenSSL
    - urllib3
  become: true
  tags:
    - common
