---

- name: Update and upgrade Homebrew packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  become: false
  tags:
    - common

- name: Install common utils
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
  tags:
    - common
