---

- include_vars: ../vars/main-{{ ansible_distribution }}.yml
  tags:
    - common

- name: Set FQDN
  set_fact:
    mediacloud_fqdn: "{{ mediacloud_hostname }}.{{ mediacloud_domainname }}"
  tags:
    - common
    - set-hostname  # skipped on Docker

- name: Set hostname
  hostname:
    name: "{{ mediacloud_hostname }}"
  become: true
  notify:
    - Restart hostname
    - Restart systemd-logind
  tags:
    - common
    - set-hostname  # skipped on Docker

- name: Add FQDN to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1\\s+{{ mediacloud_fqdn }}\\s+{{ mediacloud_hostname }}"
    line: "127.0.0.1 {{ mediacloud_fqdn }} {{ mediacloud_hostname }}"
    state: present
  become: true
  notify:
    - Restart hostname
    - Restart systemd-logind
  tags:
    - common
    - set-hostname  # skipped on Docker

- name: Re-gather facts after setting hostname + domainname
  action: setup
  when: "ansible_fqdn != mediacloud_fqdn"
  tags:
    - common
    - set-hostname  # skipped on Docker

- name: Install locales package
  apt:
    name: locales
    state: present
    install_recommends: false
  become: true
  tags:
    - common

- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mediacloud_locale_lang }}"
    - "{{ mediacloud_locale_lang }}.{{ mediacloud_locale_lang_variant }}"
  become: true
  tags:
    - common

- name: Update locale
  command: >
    update-locale
    LANG={{ mediacloud_locale_lang }}.{{ mediacloud_locale_lang_variant }}
    LANGUAGE={{ mediacloud_locale_lang }}
  become: true
  changed_when: false
  tags:
    - common

- name: Install tzdata package
  apt:
    name: tzdata
    state: present
    install_recommends: false
  become: true
  tags:
    - common

# "timezone" doesn't work in Docker containers (due to the lack of systemd?)
- name: Set timezone
  block:

    - name: Write timezone to /etc/timezone
      copy:
        content: "{{ mediacloud_timezone }}"
        dest: /etc/timezone
      become: true
      notify:
        - Restart cron  # for cron jobs to fire at the right time
      tags:
        - common

    - name: Symlink timezone to /etc/localtime
      file:
        src: "/usr/share/zoneinfo/{{ mediacloud_timezone }}"
        dest: /etc/localtime
        state: link
      become: true
      notify:
        - Restart cron
      tags:
        - common

    - name: Reconfigure locales
      command: dpkg-reconfigure -f noninteractive tzdata
      become: true
      notify:
        - Restart cron
      tags:
        - common

- name: Install common utils
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  with_items:
    - bash-completion
    - git
    - htop
    - python-software-properties
    - vim
  become: true
  tags:
    - common

- name: Install Pip
  apt:
    name: python-pip
    state: present
    install_recommends: false
  become: true
  tags:
    - common

- name: Install Python packages for validating SSL certificates with SNI
  pip:
    name: supervisor
  with_items:
    - ndg-httpsclient
    - pyasn1
    - pyOpenSSL
    - urllib3
  become: true
  tags:
    - common

- name: Set Vim as default system-wide editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  args:
    creates: /etc/alternatives/editor
  become: true
  tags:
    - common

- name: Set Vim as default user editor
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.selected_editor"
    regexp: "^SELECTED_EDITOR=.+?$"
    line: 'SELECTED_EDITOR="/usr/bin/vim.basic"'
    create: true
    state: present
  become: false
  tags:
    - common
