# For whatever reason having handlers in separate per-OS files doesn't work in Ansible 2.3

- name: Restart PostgreSQL (MacOSX)
  command: "brew services restart postgresql"
  tags:
    - postgresql-server

- name: "Restart PostgreSQL (Ubuntu)"
  service: 
    name: postgresql
    state: restarted
  become: true
  tags:
    - postgresql-server

- name: restart postgresql
  debug:
    msg: "restart postgresql"
  notify:
    - "Restart PostgreSQL ({{ ansible_distribution }})"
  changed_when: true
  tags:
    - postgresql-server
