---

- name: Install PostgreSQL
  homebrew:
    name: postgresql
    state: present
  tags:
    - postgresql-server

- name: Start and enable PostgreSQL
  command: brew services start postgresql
  args:
    creates: "{{ ansible_env.HOME }}/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
  tags:
    - postgresql-server

- name: Install psycopg2 for managing PostgreSQL users
  pip:
    name: psycopg2
  tags:
    - postgresql-server
