- include_vars: ../vars/main-{{ ansible_distribution }}.yml

- include: main-{{ ansible_distribution }}.yml

- name: Create PostgreSQL user for current user
  postgresql_user:
    name: "{{ ansible_user }}"

    login_user: "{{ postgresql_psql_login_user }}"
  become: "{{ postgresql_psql_become }}"
  become_user: "{{ postgresql_psql_become_user }}"
  tags:
    - postgresql-server

- name: Create PostgreSQL database for current user
  postgresql_db:
    name: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"

    # Force UTF-8 encoding because some PostgreSQL installations default to
    # "LATIN1" and then LENGTH() and similar functions don't work correctly
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

    # "template1" is preinitialized with "LATIN1" encoding on some systems and
    # doesn't work, so using a cleaner "template0":
    template: template0

    login_user: "{{ postgresql_psql_login_user }}"
  become: "{{ postgresql_psql_become }}"
  become_user: "{{ postgresql_psql_become_user }}"
  tags:
    - postgresql-server
