---

- name: Test if GCC is installed
  stat:
    path: /usr/bin/gcc
  register: have_gcc
  tags:
    - system-packages

- name: Fail if GCC is not installed
  fail:
    msg: >
      As a dependency to Homebrew, you need to install Xcode (available as a free
      download from Mac App Store or from http://developer.apple.com/) and Xcode's
      "Command Line Tools" (open Xcode, go to "Xcode" -> "Preferences...", select
      "Downloads", choose "Components", click "Install" near the "Command Line Tools"
      entry, wait for a while.
  when: have_gcc.stat.executable is not defined or have_gcc.stat.executable == False
  tags:
    - system-packages

- name: Install system packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options }}"
    state: present
  with_items:
    - { name: coreutils, install_options: null }
    - { name: cpanminus, install_options: null }
    - { name: curl, install_options: null }
    - { name: gawk, install_options: null }
    - { name: hunspell, install_options: null }
    - { name: libyaml, install_options: null }
    - { name: logrotate, install_options: null }
    - { name: mecab, install_options: null }
    - { name: netcat, install_options: null }
    - { name: openssl, install_options: null }
    - { name: perl, install_options: null }
    - { name: python, install_options: null }
    - { name: rabbitmq, install_options: null }
    - { name: tidy-html5, install_options: null }
  tags:
    - system-packages

- name: Install Python 3.5
  command: "brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ec545d45d4512ace3570782283df4ecda6bb0044/Formula/python3.rb"
  args:
    creates: "/usr/local/bin/python3.5"
  tags:
    - system-packages

- name: Switch to Python 3.5
  command: brew switch python3 3.5.2_3
  tags:
    - system-packages

- name: Install dependencies for Graphviz
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - fontconfig
    - freetype
    - gd
    - pcre
    - pkg-config
    - ruby
    - swig
    - webp
  tags:
    - system-packages

- name: Install Graphviz with Perl bindings
  command: "brew install --verbose graphviz --with-bindings"
  args:
    creates: "/usr/local/Cellar/graphviz/*/lib/graphviz/perl/libgv_perl.so"
  tags:
    - system-packages
